
GET  http://localhost:3001/app/notes
###
POST  http://localhost:3001/app/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZWZiNjQzNmMwNzc3MzIxNjk4ODYwMSIsImlhdCI6MTY0MzExMDgyNn0.CP0k2z5JKKgq-Vl3AmQ4UOZCktHBpy_QKXJFhHj3AME

{
    "content":"from vcs for kirikhan",
    "important":false
}

###

post http://localhost:3001/app/users/
Content-Type: application/json

{
    "notes": [],
    "userName": "abbass",
    "name": "abbass",
    "password": "salam"
}

###  
post http://localhost:3001/app/login
Content-Type: application/json

{
    "username": "shamort",
    "name": "shamort",
    "password": "salam"
}